export const APP = {
    SET_STATE: "SET_STATE",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
    
    LANG: {
        RUS: "rus",
        ENG: "eng",
    },
    
    STATE: {
        EDIT: "EDIT"
    }  
} 

export const TILESET_AREA = {
    SET_SIZE: "SET_SIZE",
    SET_PEN_AREA: "SET_PEN_AREA",
    LEVEL: {
        SET_SIZE: "LEVEL_SET_SIZE",
        SET_TILE_SIZE: "LEVEL_SET_TILE_SIZE",
    },
    INSTR: {
        PEN: "PEN",
        ERASE: "ERASE",
        SET_INSTR: "SET_INSTR"
    }
}

export const TILESET_LOADER = {
    LOAD_TILESET: "LOAD_TILESET",
    SET_CURRENT: "SET_CURRENT_TILESET",
    TILESET_SET_WIDTH: "TILESET_SET_WIDTH",
    TILESET_SET_HEIGHT: "TILESET_SET_HEIGHT",
    TILESET_SET_OFFSET_X: "TILESET_SET_OFFSET_X",
    TILESET_SET_OFFSET_Y: "TILESET_SET_OFFSET_Y",
    TILESET_SET_SEP_X: "TILESET_SET_SEP_X",
    TILESET_SET_SEP_Y: "TILESET_SET_SEP_Y",
}

export const TILESET_SETTINGS = {
    ASSIGN_INPUT_VALUES: "ASSIGN_INPUT_VALUES",
    LEFT_PERC: 0.75
}